before_script:
  - gem install xcpretty

types:
  - test

Timber:
  type: test
  script:
    - xcodebuild -verbose -scheme Timber-iOS -destination "platform=iOS Simulator,name=iPhone 6 Plus,OS=9.1" test | xcpretty -c
    - xcodebuild -verbose -scheme Timber-tvOS -destination "platform=tvOS Simulator,name=Apple TV 1080p" test | xcpretty -c
