name: "Timber"
options:
  minimumXcodeGenVersion: 2.8.0
  bundleIdPrefix: io.hecho
  deploymentTarget:
    iOS: 10.0
    macOS: 10.12
  indentWidth: 4
  tabWidth: 4
  usesTabs: true

settingGroups:
  app:
    DEVELOPMENT_TEAM: FX8EL9YD72
    INFOPLIST_FILE: "Sources/Timber/Supporting Files/Info.plist"    
    ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: $(inherited)

configs:
  Debug: debug  
  Release: release

targets:
  Timber:    
    type: framework
    platform: 
      - iOS
      - macOS
      - tvOS
    sources:
      - Sources/Timber
    scheme:
      testTargets:
        - TimberTests_${platform}
      gatherCoverageData: true
    settings:
      groups:        
        - app
      base:        
        PRODUCT_BUNDLE_IDENTIFIER: io.hecho.timber
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "iPhone Developer"          
        Release:
          CODE_SIGN_IDENTITY: "iPhone Distribution"          
    postCompileScripts:
      - path: Scripts/swiftlint.sh
        name: Run SwiftLint

  TimberTests:
    type: bundle.unit-test
    platform: 
      - iOS
      - macOS
      - tvOS
    sources: Sources/TimberTests
    dependencies:
      - target: Timber_${platform}      